### ISSUE TITLE
I have a problem to swap two username

### ISSUE THREAD

**Issue by thesandwish** [qxxa/instaclaimer#1]
Hi mister, I used your tool to swap two usernames but I failed.

I entered everything correctly username password and before I start the tool I went to instagram to my account and changed the username (the target) 
and then an error...

I don't know where I've made the mistake, it could be because I entered a lot of threads (I did 20)
or maybe because I changed my username before running the tool.
btw I don't have proxies.

Thanks mister.

_thesandwish_

**Comment by thesandwish** [comment]
I understand now, I'll wait the 14 days and then I'll use the auto-claimer.
Personally I know nothing about programming but I like to get my hands dirty sometimes.

Thanks again mister for sharing this script and for replaying.

thesandwish

**Comment by qxxa** [comment]
You're most welcome, @thesandwish! I'm glad I could help clarify your doubts.

I'll try to make a video on how to use the tool, which should makes things even easier.
