### ISSUE TITLE
Username available Unexpected Error: list index out of range

### ISSUE THREAD

**Issue by Ashwin3454** [qxxa/instaclaimer#3]

**Comment by qxxa** [comment]
Can you provide me with a screenshot of the issue and some details?

**Comment by qxxa** [comment]
Your account is rate limited by Instagram because too many requests were sent in a short amount of time. Wait a few hours before trying again or use a different account.

Also, if you are not using proxies, try reducing the number of threads. Around 5 threads should be good enough.

**Comment by qxxa** [comment]
Yeah bro I've already started work on the checker, but it will take some time to complete.
